# Site info
title = "InfluxDB"
baseurl = "http://new.influxdb.com/"

# Site configuration
languageCode = "en-US"
config = "config.toml"
publishdir = "public"
contentdir = "content"
layoutdir = "layouts"

# Use urls that end in .html
uglyurls = true

# Site links
[permalinks]
  site = "/:filename/index.html"

[params]
  CustomersUrl = "https://acceptance.influxdb.com"
  StripeApiToken = "pk_test_raFtCBUQIROL9yvZdgFy532f"
